[package]
name = "alayasiki-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
publish = false

[dependencies]
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "time"] }
config = "0.14"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rkyv.workspace = true
bytes = "1.0"
sha2.workspace = true
jsonwebtoken.workspace = true

[dev-dependencies]
tempfile.workspace = true
